"""
Agent state definitions.

This module defines the state structure passed through the LangGraph nodes.
"""

from typing import Any, TypedDict


class AgentState(TypedDict, total=False):
    """
    The state passed through the agent graph.

    This TypedDict defines all fields that can be present in the agent state.
    Using total=False allows fields to be optional.

    Attributes:
        input: The original user input.
        session_id: Session identifier for conversation continuity.
        plan: The plan generated by the planner node.
        output: The final output from the executor node.
        messages: List of conversation messages (for future use).
        metadata: Additional metadata about the run.
        error: Any error that occurred during execution.
    """

    input: str
    session_id: str
    plan: str | None
    output: str
    messages: list[dict[str, Any]]
    metadata: dict[str, Any]
    error: str | None

